# Generated by Django 3.2 on 2023-07-31 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/dp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.jpeg', '.png'])])),
                ('is_super_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/dp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.jpeg', '.png'])])),
                ('registration', models.IntegerField(primary_key=True, serialize=False)),
                ('cgpa', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['registration'],
            },
        ),
    ]
