# Generated by Django 3.2 on 2023-07-31 14:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/dp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.jpeg', '.png'])])),
                ('registration', models.IntegerField(primary_key=True, serialize=False)),
                ('cgpa', models.FloatField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results.session')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registration'],
            },
        ),
        migrations.CreateModel(
            name='InviteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('expiration', models.DateTimeField()),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/dp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.jpg', '.jpeg', '.png'])])),
                ('is_super_admin', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='results.department')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.invitetoken')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
