# Generated by Django 4.2.3 on 2023-07-31 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/dp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='studentaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/dp/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
