# Generated by Django 4.2.3 on 2023-08-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_adminaccount_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='adminaccount',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('dept__isnull', True), ('is_super_admin', True)), models.Q(('dept__isnull', False), ('is_super_admin', False)), _connector='OR'), name='admin_user_is_not_a_dept_user'),
        ),
    ]
