# Generated by Django 4.2.3 on 2023-08-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_adminaccount_admin_user_is_not_a_dept_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
