# Generated by Django 4.2.3 on 2023-08-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_studentaccount_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='is_regular',
            field=models.BooleanField(default=True),
        ),
    ]
