# Generated by Django 4.2.3 on 2023-08-20 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_cgpa_studentaccount_credits_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccount',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.invitetoken'),
        ),
    ]
