# Generated by Django 4.2.3 on 2023-08-20 15:44

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_adminaccount_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetoken',
            name='id',
            field=models.CharField(default=account.models.InviteToken.get_uuid, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
