# Generated by Django 4.2.3 on 2023-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_invitetoken_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitetoken',
            name='to_user_dept_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
