# Generated by Django 4.2.3 on 2024-01-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_studentaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('sust', 'Sust Admin')], max_length=10, null=True),
        ),
    ]
