# Generated by Django 4.2.3 on 2024-01-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_invitetoken_actype'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adminaccount',
            name='admin_user_is_not_a_dept_user',
        ),
    ]
