# Generated by Django 4.2.3 on 2024-01-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_adminaccount_admin_user_is_not_a_dept_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccount',
            name='father_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentaccount',
            name='mother_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
