# Generated by Django 4.2.3 on 2024-02-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_studentaccount_father_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('sust', 'Sust Admin'), ('academic', 'SEC Academic')], max_length=10, null=True),
        ),
    ]
