name: Server Update and Reload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/rony/sec_ugrp/
            git pull origin
            source venv/bin/activate
            python manage.py migrate
            python manage.py collectstatic --noinput
            systemctl reload-or-restart uwsgi